<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use SaltProduct\Models\Variants;
use SaltProduct\Models\VariantUnits;
use Illuminate\Support\Str;

class VariantsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $variants = [
            ['id' => Str::uuid()->toString(), 'type' => 'color', 'name' => 'Warna'],
            ['id' => Str::uuid()->toString(), 'type' => 'size', 'name' => 'Ukuran'],
            ['id' => Str::uuid()->toString(), 'type' => 'tool', 'name' => 'Alat Perkakas'],
        ];

        Variants::insert($variants);

        // variant_units
        $variant = Variants::where('type', 'color') ->first();
        // VALUES: putih, hitam, biru, biru muda, merah, merah muda, orange, kuning, cokelat, hijau, ungu, abu-abu, cream,
        $uid = $variant->id;
        $units = [
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'color',
                'name' => 'color',
                'is_primary' => true,
                'status' => 'inactive',
                'label' => 'Putih',
                'label_english' => 'White',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'color',
                'name' => 'color',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => 'Hitam',
                'label_english' => 'Black',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'color',
                'name' => 'color',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => 'Biru',
                'label_english' => 'Blue',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'color',
                'name' => 'color',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => 'Biru Muda',
                'label_english' => 'Light Blue',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'color',
                'name' => 'color',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => 'Merah',
                'label_english' => 'Red',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'color',
                'name' => 'color',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => 'Merah Muda',
                'label_english' => 'Pink',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'color',
                'name' => 'color',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => 'Oranye',
                'label_english' => 'Orange',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'color',
                'name' => 'color',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => 'Kuning',
                'label_english' => 'Yellow',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'color',
                'name' => 'color',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => 'Cokelat',
                'label_english' => 'Brown',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'color',
                'name' => 'color',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => 'Hijau',
                'label_english' => 'Green',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'color',
                'name' => 'color',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => 'Ungu',
                'label_english' => 'Purple',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'color',
                'name' => 'color',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => 'Abu-abu',
                'label_english' => 'Grey',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'color',
                'name' => 'color',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => 'Krem',
                'label_english' => 'Beige',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
        ];

        VariantUnits::insert($units);


        $variant = Variants::where('type', 'size') ->first();
        // VALUES: 0,2,4,6,8,10,12,14,16,XS,S,M,L,XL,XXL,ALLSIZE,
        $uid = $variant->id;
        $units = [
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'size',
                'name' => 'size',
                'is_primary' => true,
                'status' => 'inactive',
                'label' => '0',
                'label_english' => '0',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'size',
                'name' => 'size',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '2',
                'label_english' => '2',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'size',
                'name' => 'size',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '4',
                'label_english' => '4',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'size',
                'name' => 'size',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '6',
                'label_english' => '6',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'size',
                'name' => 'size',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '8',
                'label_english' => '8',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'size',
                'name' => 'size',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '10',
                'label_english' => '10',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'size',
                'name' => 'size',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '12',
                'label_english' => '12',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'size',
                'name' => 'size',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '14',
                'label_english' => '14',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'size',
                'name' => 'size',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '16',
                'label_english' => '16',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'size',
                'name' => 'size',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => 'XS',
                'label_english' => 'XS',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'size',
                'name' => 'size',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => 'S',
                'label_english' => 'S',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'size',
                'name' => 'size',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => 'M',
                'label_english' => 'M',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'size',
                'name' => 'size',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => 'L',
                'label_english' => 'L',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'size',
                'name' => 'size',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => 'XL',
                'label_english' => 'XL',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'size',
                'name' => 'size',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => 'XXL',
                'label_english' => 'XXL',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'size',
                'name' => 'size',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => 'ALL SIZE',
                'label_english' => 'ALL SIZE',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
        ];

        VariantUnits::insert($units);


        $variant = Variants::where('type', 'tool') ->first();
        // Berat: 1g, 2g, 4g, 5g, 10g, 25g, 50g, 70g, 100g, 200g, 400g, 500g, 600g, 700g, 800g, 900g, 1kg, 2kg, 3kg, 4kg, 5kg, 2.5kg,
        // Diameter: 16cm, 18cm, 20cm, 22cm, 24cm, 26cm, 28cm, 30cm,
        // Dimensi: 90x60 cm, 70x45 cm, 40x65 cm, 30x40 cm,
        // Volume: 10ml, 25ml, 50ml, 100ml, 250ml, 500ml, 600ml, 800ml, 1l,2l,3l,4l,5l,16l,17l,18l,19l,20l,26l,27l,28l,29l,30l,36l,37l,38l,39l,40l,
        $uid = $variant->id;
        $units = [
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => true,
                'status' => 'inactive',
                'label' => '1g',
                'label_english' => '1g',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '2g',
                'label_english' => '2g',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '4g',
                'label_english' => '4g',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '5g',
                'label_english' => '5g',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '10g',
                'label_english' => '10g',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '25g',
                'label_english' => '25g',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '50g',
                'label_english' => '50g',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '70g',
                'label_english' => '70g',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '100g',
                'label_english' => '100g',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '200g',
                'label_english' => '200g',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '400g',
                'label_english' => '400g',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '500g',
                'label_english' => '500g',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '600g',
                'label_english' => '600g',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '700g',
                'label_english' => '700g',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '800g',
                'label_english' => '800g',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '900g',
                'label_english' => '900g',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '1kg',
                'label_english' => '1kg',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '2kg',
                'label_english' => '2kg',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '3kg',
                'label_english' => '3kg',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '4kg',
                'label_english' => '4kg',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '5kg',
                'label_english' => '5kg',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'weight',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '2.5kg',
                'label_english' => '2.5kg',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],


            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'diameter',
                'is_primary' => true,
                'status' => 'inactive',
                'label' => '016cm',
                'label_english' => '016cm',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'diameter',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '18cm',
                'label_english' => '18cm',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'diameter',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '20cm',
                'label_english' => '20cm',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'diameter',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '22cm',
                'label_english' => '22cm',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'diameter',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '24cm',
                'label_english' => '24cm',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'diameter',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '26cm',
                'label_english' => '26cm',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'diameter',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '28cm',
                'label_english' => '28cm',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'diameter',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '30cm',
                'label_english' => '30cm',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],


            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'dimension',
                'is_primary' => true,
                'status' => 'inactive',
                'label' => '90x60 cm',
                'label_english' => '90x60 cm',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'dimension',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '70x45 cm',
                'label_english' => '70x45 cm',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'dimension',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '40x65 cm',
                'label_english' => '40x65 cm',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'dimension',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '30x40 cm',
                'label_english' => '30x40 cm',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],


            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => true,
                'status' => 'inactive',
                'label' => '10ml',
                'label_english' => '10ml',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '25ml',
                'label_english' => '25ml',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '50ml',
                'label_english' => '50ml',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '100ml',
                'label_english' => '100ml',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '250ml',
                'label_english' => '250ml',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '500ml',
                'label_english' => '500ml',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '600ml',
                'label_english' => '600ml',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '800ml',
                'label_english' => '800ml',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '1l',
                'label_english' => '1l',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '2l',
                'label_english' => '2l',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '3l',
                'label_english' => '3l',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '4l',
                'label_english' => '4l',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '5l',
                'label_english' => '5l',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '16l',
                'label_english' => '16l',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '17l',
                'label_english' => '17l',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '18l',
                'label_english' => '18l',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '19l',
                'label_english' => '19l',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '20l',
                'label_english' => '20l',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '26l',
                'label_english' => '26l',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '27l',
                'label_english' => '27l',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '28l',
                'label_english' => '28l',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '29l',
                'label_english' => '29l',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '30l',
                'label_english' => '30l',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '36l',
                'label_english' => '36l',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '37l',
                'label_english' => '37l',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '38l',
                'label_english' => '38l',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '39l',
                'label_english' => '39l',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
            [
                'id' => Str::uuid()->toString(),
                'variant_id' => $uid,
                'type' => 'tool',
                'name' => 'volume',
                'is_primary' => false,
                'status' => 'inactive',
                'label' => '40l',
                'label_english' => '40l',
                'hex' => null,
                'icon' => null,
                'price' => 0,
                'stock' => 1,
                'sku' => null,
                'weight' => 0,
            ],
        ];

        VariantUnits::insert($units);

    }
}
